name: gis_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - geopandas
  - rasterio
  - rasterstats
  - scikit-learn
  - shapely
  - fiona
  - gdal
  - pyproj
  - jupyterlab
  - ipykernel
